### PR TITLE
Pierpaolocira patch add desctiption support

### PR DESCRIPTION
**Pull request by pierpaolocira**
This is my request for issue #21 
As I wrote in my comments, I thought the best solution to achieve what I need for is to add a "description" support, implemented in the same way of "adjunct"s.
You can see a working example in "demo" folder and at the final part of README.

### CODE REVIEW

**Comment by caprica** [comment]
Some of those commits could be squashed I think.

**Comment by pierpaolocira** [comment]
Sorry, now it is squashed... please, let me know... :)

**Comment by caprica** [comment]
Sorry for the delay, I am still interested in this. I have not forgotten about it and hope to review it soon.

**Comment by pierpaolocira** [comment]
No problem: I only hope it can be useful. :)

**Comment by pierpaolocira** [comment]
Hi, any news? :)

**Comment by caprica** [comment]
Closing since all future work will go into the react-org-chart project instead.

**Pull request closed without merging**
