### PR TITLE
Added vertical direction, and one sample

### PR DESCRIPTION
**Pull request by wh1tew0lf**
For my project I need to show parent node at bottom, but childs at top. I add one field - verticalDirection, for set how org chart will be drown from top to bottom, or from bottom to top. I think it is usefull

### CODE REVIEW

**Comment by caprica** [comment]
Out of curiosity, what is the use-case for an inverted chart like this?

**Comment by thiazzz** [comment]
Is it possible to create a more condensed view of the org chart, like in this example:
https://www.dropbox.com/s/osl1eh280qs8mde/Screenshot%202015-03-20%2011.53.53.png?dl=0

**Comment by caprica** [comment]
I don't think that question is related to this pull request.

Fundamentally, that type of chart can not be produced (now) because it has chart nodes drawn to the side of a line.

The closest you can get to that with the orgchart plugin now is to use the "stacking" feature, and see if you can do anything clever with CSS to get the effect you want with the lateral lines.

**Comment by wh1tew0lf** [comment]
For the code formatting and names - I agree I will fix it, but think I tried to use your format at all.
For an inverted chart use-case - my client ask me do it. We work on generating play-off schema and he want to see it from first mathes to final. I tried to find something usefull, and found only http://www.getorgchart.com/ - this solution.
Other idea - family tree.

**Comment by wh1tew0lf** [comment]
Try it now, I have fixed all comments.

**Comment by caprica** [comment]
Thanks, I'll review it soon and hopefully apply. I prefer to apply it as a patch rather than a pull request so don't be shocked if the request gets closed.

**Comment by caprica** [comment]
So to test this I checked it against the charts on my company web-site.

Unfortunately I see some glitches...

Here you can see on the right hand side the vertical line is out:

chart-glitch-1

This one I'm not sure about, is that a stacked bottom-to-top chart should look like?

chart-glitch-2

Same as the first glitch I suppose, the vertical lines don't all line up:

chart-glitch-3

**Pull request closed without merging**
